---
- name: Debug auth info
  debug:
    msg:
      - "Auth kind: {{ gcp_auth_kind }}"
      - "Project: {{ gcp_project }}"
      - "Service account: {{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"

- name: Get current identity
  shell: gcloud config list account --format "value(core.account)"
  register: gcloud_identity

- name: Show current identity
  debug:
    msg: "Current gcloud identity: {{ gcloud_identity.stdout }}"

- name: Create GKE cluster
  google.cloud.gcp_container_cluster:
    name: tennis-predictor-cluster-2
    location: us-central1-a
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file if gcp_auth_kind == 'serviceaccount' else omit }}"
    scopes: "{{ gcp_scopes }}"
    initial_node_count: 3
    node_config:
      machine_type: e2-medium
      disk_size_gb: 100
      oauth_scopes:
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
        - https://www.googleapis.com/auth/servicecontrol
        - https://www.googleapis.com/auth/service.management.readonly
        - https://www.googleapis.com/auth/trace.append
    state: present

- name: Add GPU node pool
  google.cloud.gcp_container_node_pool:
    name: l4-gpu-pool
    cluster:
      name: tennis-predictor-cluster-2
      location: us-central1-a
    location: us-central1-a
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file if gcp_auth_kind == 'serviceaccount' else omit }}"
    initial_node_count: 1
    # max node count is 1
    autoscaling:
      enabled: true
      min_node_count: 1
      max_node_count: 1
    config:
      machine_type: g2-standard-4
      disk_size_gb: 100
      oauth_scopes:
        - https://www.googleapis.com/auth/devstorage.read_only
        - https://www.googleapis.com/auth/logging.write
        - https://www.googleapis.com/auth/monitoring
      accelerators:
        - accelerator_count: 1
          accelerator_type: nvidia-l4
    state: present

- name: Get cluster credentials
  shell: >
    gcloud container clusters get-credentials tennis-predictor-cluster-2
    --zone us-central1-a
    --project {{ gcp_project }}
