_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-aarch64
batch_size:
    value: 32
hidden_size:
    value: 32
learning_rate:
    value: 0.001
num_epochs:
    value: 10
num_layers:
    value: 2
test_size:
    value: 0.2
