---
- name: Create default namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: default

- name: Apply k8s configurations
  kubernetes.core.k8s:
    state: present
    src: ../../src/k8s-config.yaml
    namespace: default

- name: Deploy API
  kubernetes.core.k8s:
    state: present
    namespace: default
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: api
        template:
          metadata:
            labels:
              app: api
          spec:
            containers:
              - name: api
                image: gcr.io/tennis-match-predictor/api
                ports:
                  - containerPort: 8000
                envFrom:
                  - configMapRef:
                      name: tennis-env
# Add similar tasks for probability-model, llm, and ollama deployments
