export const players = [
  {
    id: "Roger Federer",
    name: "Roger Federer",
    age: "43 (1981/08/08)",
    country: "Switzerland",
    height: "6'1\" (185cm)",
    weight: "187 lbs (85kg)",
    imageUrl: "/images/roger_federer.png",
  },
  {
    id: "Rafael Nadal",
    name: "Rafael Nadal",
    age: "38 (1986/06/03)",
    country: "Spain",
    height: "6'1\" (185cm)",
    weight: "187 lbs (85kg)",
    imageUrl: "/images/rafael_nadal.png",
  },
  {
    id: "Jannik Sinner",
    name: "Jannik Sinner",
    age: "23 (2001/08/16)",
    country: "Italy",
    height: "6'3\" (191cm)",
    weight: "170 lbs (77kg)",
    imageUrl: "/images/jannik_sinner.png",
  },
  {
    id: "Pablo Cuevas",
    name: "Pablo Cuevas",
    age: "38 (1986/01/01)",
    country: "Uruguay",
    height: "5'11\" (180cm)",
    weight: "173 lbs (78kg)",
    imageUrl: "/images/pablo_cuevas.png",
  },
  {
    id: "Carlos Alcaraz",
    name: "Carlos Alcaraz",
    age: "21 (2003/05/05)",
    country: "Spain",
    height: "6'0\" (183cm)",
    weight: "163 lbs (74kg)",
    imageUrl: "/images/carlos_alcaraz.png",
  },
  {
    id: "Taylor Fritz",
    name: "Taylor Fritz",
    age: "27 (1997/10/28)",
    country: "United States",
    height: "6'5\" (196cm)",
    weight: "190 lbs (86kg)",
    imageUrl: "/images/taylor_fritz.png",
  },
  {
    id: "Casper Ruud",
    name: "Casper Ruud",
    age: "25 (1998/12/22)",
    country: "Norway",
    height: "6'0\" (183cm)",
    weight: "178 lbs (81kg)",
    imageUrl: "/images/casper_ruud.png",
  },
  {
    id: "Novak Djokovic",
    name: "Novak Djokovic",
    age: "37 (1987/05/22)",
    country: "Serbia",
    height: "6'2\" (188cm)",
    weight: "170 lbs (77kg)",
    imageUrl: "/images/casper_ruud.png",
  },
  {
    id: "Alex De Minaur",
    name: "Alex De Minaur",
    age: "25 (1999/02/17)",
    country: "Australia",
    height: "6'0\" (183cm)",
    weight: "152 lbs (69kg)",
    imageUrl: "/images/alex_de_minaur.png",
  },
  {
    id: "Grigor Dimitrov",
    name: "Grigor Dimitrov",
    age: "33 (1991/05/16)",
    country: "Bulgaria",
    height: "6'3\" (191cm)",
    weight: "179 lbs (81kg)",
    imageUrl: "/images/grigor_dimitrov.png",
  },
];
