version: "3.8"

services:
  web:
    build:
      context: ./frontend/tennis-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/super-admin-key.json
      - GCP_PROJECT=tennis-match-predictor
      - GCP_ZONE=us-central1-a
      - GCS_BUCKET_NAME=msmballstars-data
    networks:
      - msmballstars-network
    volumes:
      - ./api:/app
      - ./.env.dev:/app/.env.dev
      - ../../secrets:/secrets
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: .env.dev
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - PORT=${API_PORT:-8000}
      - MODEL_HOST=probability_model
      - MODEL_PORT=${MODEL_PORT:-8001}
      - LLM_HOST=llm
      - LLM_PORT=${LLM_PORT:-8002}
      - ENV=dev
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/super-admin-key.json
      - GCP_PROJECT=tennis-match-predictor
      - GCP_ZONE=us-central1-a
      - GCS_BUCKET_NAME=msmballstars-data
      - DATA_FOLDER=version1
      - DATA_FILE=combined_atp_matches.csv
    networks:
      - msmballstars-network
    volumes:
      - ./api:/app
      - ./.env.dev:/app/.env.dev
      - ../../secrets:/secrets
    depends_on:
      - probability_model
      - llm

  probability_model:
    build:
      context: ./probability_model
      dockerfile: Dockerfile
    env_file: .env.dev
    ports:
      - "${MODEL_PORT:-8001}:${MODEL_PORT:-8001}"
    environment:
      - PORT=${MODEL_PORT:-8001}
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/super-admin-key.json
      - GCP_PROJECT=tennis-match-predictor
      - GCP_ZONE=us-central1-a
      - GCS_BUCKET_NAME=msmballstars-data
      - DATA_FOLDER=version1
      - DATA_FILE=training_data_lookback=10.pkl
      - WEIGHTS_FILE=prob_model.pt
      - HIDDEN_SIZE=32
      - NUM_LAYERS=2
      - CUDA_VISIBLE_DEVICES=""
      - TORCH_DEVICE=cpu
    networks:
      - msmballstars-network
    volumes:
      - ./probability_model:/app
      - ./.env.dev:/app/.env.dev
      - ../../secrets:/secrets

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    env_file: .env.dev
    ports:
      - "${LLM_PORT:-8002}:${LLM_PORT:-8002}"
    environment:
      - PORT=${LLM_PORT:-8002}
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/super-admin-key.json
      - GCP_PROJECT=tennis-match-predictor
      - GCP_ZONE=us-central1-a
      - GCS_BUCKET_NAME=msmballstars-data
    depends_on:
      - ollama
    networks:
      - msmballstars-network
    volumes:
      - ./llm:/app
      - ./.env.dev:/app/.env.dev
      - ../../secrets:/secrets

  ollama:
    build:
      context: ./llm
      dockerfile: ollama.Dockerfile
    ports:
      - "11434"
    networks:
      - msmballstars-network
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:

networks:
  msmballstars-network:
    driver: bridge
