version: "3.8"
services:
  model_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MODEL_PORT}:${MODEL_PORT}"  # Use environment variables here
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - GCP_PROJECT=${GCP_PROJECT}
      - GCP_ZONE=${GCP_ZONE}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - DATA_FOLDER=${DATA_FOLDER}
      - DATA_FILE=${DATA_FILE}
      - HIDDEN_SIZE=${HIDDEN_SIZE}
      - NUM_LAYERS=${NUM_LAYERS}
      - ENV=${ENV}
      - PORT=${MODEL_PORT}
    volumes:
      - .:/app
      - ../../../secrets:/secrets
