name: Deploy to GKE

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  workflow_dispatch:

env:
  PROJECT_ID: tennis-match-predictor
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible requests google-auth openshift pyyaml kubernetes
          ansible-galaxy collection install google.cloud kubernetes.core

      - name: Run Ansible Playbook
        env:
          CI: "true"
        run: |
          cd src/ansible
          ansible-playbook site.yml
