name: Deploy to GKE

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  workflow_dispatch:

env:
  PROJECT_ID: tennis-match-predictor
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build and Push API Container
        run: |
          cd src/api
          docker build -t gcr.io/$PROJECT_ID/api:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/api:${{ github.sha }}
          # Also tag as latest
          docker tag gcr.io/$PROJECT_ID/api:${{ github.sha }} gcr.io/$PROJECT_ID/api:latest
          docker push gcr.io/$PROJECT_ID/api:latest

      - name: Build and Push Probability Model Container
        run: |
          cd src/probability_model
          docker build -t gcr.io/$PROJECT_ID/probability-model:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/probability-model:${{ github.sha }}
          # Also tag as latest
          docker tag gcr.io/$PROJECT_ID/probability-model:${{ github.sha }} gcr.io/$PROJECT_ID/probability-model:latest
          docker push gcr.io/$PROJECT_ID/probability-model:latest

      - name: Build and Push LLM Container
        run: |
          cd src/llm
          docker build -t gcr.io/$PROJECT_ID/llm:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/llm:${{ github.sha }}
          # Also tag as latest
          docker tag gcr.io/$PROJECT_ID/llm:${{ github.sha }} gcr.io/$PROJECT_ID/llm:latest
          docker push gcr.io/$PROJECT_ID/llm:latest

      - name: Build and Push Ollama Container
        run: |
          cd src/llm
          docker build -f ollama.Dockerfile -t gcr.io/$PROJECT_ID/ollama:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/ollama:${{ github.sha }}
          # Also tag as latest
          docker tag gcr.io/$PROJECT_ID/ollama:${{ github.sha }} gcr.io/$PROJECT_ID/ollama:latest
          docker push gcr.io/$PROJECT_ID/ollama:latest

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud components update

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible requests google-auth openshift pyyaml kubernetes
          ansible-galaxy collection install google.cloud kubernetes.core

      - name: Run Ansible Playbook
        env:
          CI: "true"
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd src/ansible
          ansible-playbook site.yml
