name: Firebase Deploy

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Adjust Node.js version as per your project's requirement

      # Step 3: Navigate to the React project directory
      - name: Change to frontend project directory
        run: cd src/frontend/tennis-app

      # Step 4: Install dependencies
      - name: Install dependencies
        working-directory: src/frontend/tennis-app
        run: npm install

      # Step 5: Build the project
      - name: Build the React app
        working-directory: src/frontend/tennis-app
        run: |
          CI=false npm run build

      # Step 6: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        working-directory: src/frontend/tennis-app
        run: |
          npm install -g firebase-tools
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
