name: Integration Test

on:
  push:
    branches:
      - "*"
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install test dependencies
        working-directory: src/probability_model
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Set up environment
        working-directory: src
        run: |
          mkdir -p ../../secrets
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > ../../secrets/super-admin-key.json
          ls -la ../../secrets

      - name: Run integration test
        working-directory: src
        run: |
          chmod +x integration_test.sh
          ./integration_test.sh

      - name: Print container logs on failure
        if: failure()
        working-directory: src
        run: |
          docker compose logs
          docker compose down
