name: Integration Test

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Set up environment
        run: |
          mkdir -p secrets
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > secrets/super-admin-key.json

      - name: Run integration test
        working-directory: src
        run: |
          chmod +x integration_test.sh
          ./integration_test.sh

      - name: Print container logs on failure
        if: failure()
        working-directory: src
        run: |
          docker compose logs
          docker compose down
