name: System (E2E) Test

on:
  push:
    branches:
      - "*"
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  system-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Set up environment
        working-directory: src
        run: |
          mkdir -p ../../secrets
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > ../../secrets/super-admin-key.json
          ls -la ../../secrets

      - name: Install Playwright
        working-directory: src/frontend/tennis-app
        run: |
          npm install

      - name: Run system test
        working-directory: src/system_tests
        run: |
          chmod +x system_test.sh
          ./system_test.sh

      - name: Print container logs on failure
        if: failure()
        working-directory: src
        run: |
          docker compose logs
          docker compose down 